name: Run Python Script to Monitor URL

# Bu workflow her 15 dakikada bir otomatik olarak çalışacak ve manuel olarak da tetiklenebilir
on:
  schedule:
    - cron: "*/15 * * * *"  # Her 15 dakikada bir çalıştırılır
  workflow_dispatch:  # Manuel olarak çalıştırılabilir

jobs:
  run-script:
    runs-on: ubuntu-latest  # GitHub Actions'ı çalıştıracak ortam

    steps:
      # Python ortamını kuruyoruz
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Python 3.x sürümünü kullanıyoruz

      # Selenium ve diğer gerekli bağımlılıkları yüklüyoruz
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      # Reponun içeriğini çekiyoruz
      - name: Checkout repository
        uses: actions/checkout@v2

      # Python scriptini çalıştırıyoruz
      - name: Run deneme.py script
        run: |
          # deneme.py'yi çalıştırıyoruz
          python deneme.py

      # Ana link dosyasının içeriğini kontrol ediyoruz
      - name: Check if ana_link.txt is updated
        run: |
          echo "Checking if ana_link.txt was updated:"
          cat ana_link.txt  # Dosyanın içeriğini kontrol ediyoruz
          
          # Eğer dosya güncellenmemişse, hatayı bildiriyoruz
          OLD_URL=$(cat ana_link.txt)
          NEW_URL=$(python deneme.py)  # Yeni URL'yi almak için tekrar scripti çalıştırıyoruz
          
          if [ "$OLD_URL" == "$NEW_URL" ]; then
            echo "No URL change detected in ana_link.txt"
            exit 1  # Workflow'u başarısız yapıyoruz
          else
            echo "URL successfully updated in ana_link.txt"
          fi
