name: Run Python Script and Monitor URL

on:
  schedule:
    - cron: "*/15 * * * *"  # Her 15 dakikada bir çalıştırılır
  workflow_dispatch:  # Manuel olarak çalıştırılabilir

jobs:
  run-script:
    runs-on: ubuntu-latest  # GitHub Actions'ın çalışacağı ortam

    steps:
      # Python ortamını kuruyoruz
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'  # Python 3'ün her hangi bir sürümünü kullanabiliriz

      # Gerekli Python bağımlılıklarını yükliyoruz
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium webdriver-manager

      # Reponun içeriğini çekiyoruz
      - name: Checkout repository
        uses: actions/checkout@v2

      # Python scriptini çalıştırıyoruz
      - name: Run Python script to get URL
        id: run_script
        run: |
          python deneme.py  # deneme.py'yi çalıştırıyoruz

      # URL'yi kontrol ediyoruz ve güncellenip güncellenmediğini kontrol ediyoruz
      - name: Check if URL is updated
        run: |
          # Mevcut URL'yi alıyoruz
          CURRENT_URL=$(cat ana_link.txt)
          echo "Mevcut URL: $CURRENT_URL"

          # Yeni URL'yi alıyoruz
          NEW_URL=$(python deneme.py)
          echo "Yeni URL: $NEW_URL"

          # Eğer URL değişmediyse hata mesajı veriyoruz
          if [ "$CURRENT_URL" == "$NEW_URL" ]; then
            echo "URL güncellenmedi!"
            exit 1  # Workflow'u başarısız yapıyoruz
          else
            echo "URL güncellendi!"
          fi
