name: Run Sequential Workflows

on:
  schedule:
    - cron: '0 */2 * * *' # Her 2 saatte bir çalıştırır
     workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-workflows:
    runs-on: ubuntu-latest
    steps:
      - name: Run Ana Domain Workflow
        uses: actions/github-script@v6
        with:
          script: |
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'ana-domain.yml',
              ref: 'refs/heads/main'
            })
      - name: Wait for Ana Domain Workflow to Complete
        run: sleep 10
      
      - name: Run Base Finder Workflow
        uses: actions/github-script@v6
        with:
          script: |
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'base-finder.yml',
              ref: 'refs/heads/main'
            })
      - name: Wait for Base Finder Workflow to Complete
        run: sleep 10
      
      - name: Run Mac Verisi Workflow
        uses: actions/github-script@v6
        with:
          script: |
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'mac-verisi.yml',
              ref: 'refs/heads/main'
            })
      - name: Wait for Mac Verisi Workflow to Complete
        run: sleep 10
      
      - name: Run Python Script Workflow
        uses: actions/github-script@v6
        with:
          script: |
            await github.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'python-script.yml',
              ref: 'refs/heads/main'
            })
