name: Selenium Script Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          pip install selenium webdriver-manager

      - name: Run the Selenium script
        run: |
          python selenium_script.py
        env:
          DISPLAY: ':99.0'

      - name: Upload the URL file as artifact
        uses: actions/upload-artifact@v2
        with:
          name: ana_link_file
          path: ana_link.txt
