name: Selenium Script Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run-selenium:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y chromium-chromedriver
          pip install selenium webdriver-manager

      - name: Run the Selenium script
        run: |
          python deneme.py
        env:
          DISPLAY: ':99.0'
      - name: Değişiklikleri kontrol et ve commit et
        run: |
        git config --local user.name "Github Action"
        git config --local user.email "action@github.com"
        if [ -n "$(git status --porcelain)" ]; then
          git add ana_link.txt  # Güncellenen dosyayı ekleyin.
          git commit -m "Güncellenen ana_link.txt dosyası"
          git push
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub tokeni ile authenticate ol
