name: Selenium Test

on:
  push:
    branches:
      - main  # main branch üzerinde her değişiklikte çalışacak
  pull_request:
    branches:
      - main  # main branch'a PR açıldığında çalışacak

jobs:
  selenium-job:
    runs-on: ubuntu-latest  # İşin Ubuntu üzerinde çalışmasını sağlıyoruz
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Depoyu checkout ediyoruz

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install selenium webdriver-manager

    - name: Run Python script
      run: |
        python deneme.py  # main.py dosyasını çalıştırıyoruz

    - name: Commit generated file
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add ana.link.txt
        git commit -m "Add link output"
        git push
