name: Selenium URL Redirect Checker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  selenium-job:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager

      - name: Run the Python script
        run: |
          python main.py

      - name: Upload the new_link.txt file
        uses: actions/upload-artifact@v2  # Burada sürümü v2 olarak değiştirdik
        with:
          name: new_link
          path: new_link.txt
