 name: Fetch Channels

   on:
     schedule:
       - cron: '0 * * * *'  # Her saat başı çalıştır
     workflow_dispatch:

   jobs:
     fetch-channels:
       runs-on: ubuntu-latest
       steps:
         - name: Checkout code
           uses: actions/checkout@v2

         - name: Set up Python
           uses: actions/setup-python@v2
           with:
             python-version: '3.9'

         - name: Install dependencies
           run: |
             python -m pip install --upgrade pip
             pip install requests beautifulsoup4

         - name: Run script
           run: |
             python fetch_channels.py
         
         - name: Commit and push changes
           run: |
             git config --local user.email "mm.duymazz@gmail.com"
             git config --local user.name "MDuymaz"
             git add channels.m3u
             git commit -m "Update channels.m3u"
             git push
           env:
             GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Otomatik olarak sağlanır.
