name: Run Mac Verisi

on:
  workflow_run:
    workflows: ["Run base_url.py script"]  # Ana Domain workflow'u tamamlandığında çalışacak
    types:
      - completed

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run script
      run: |
        python mac_verileri.py
        
    - name: Değişiklikleri kontrol et ve commit et
      run: |
        git config --local user.name "Github Action"
        git config --local user.email "action@github.com"
        if [ -n "$(git status --porcelain)" ]; then
          git add mac_verileri.txt  # Güncellenen dosyayı ekleyin.
          git commit -m "Mac Verileri Güncellendi."
          git push
        else
          echo "No changes to commit"
        fi
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub tokeni ile authenticate ol

    # python-script.yml workflow'unu tetiklemek
    - name: Trigger python-script.yml workflow
      if: success()  # Bu adımdan önce başarılı olursa tetiklenir
      run: |
        curl -X POST \
          -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
          -d '{"ref": "main"}' \
          https://api.github.com/repos/${{ github.repository }}/actions/workflows/python-script.yml/dispatches
